"""Model to CMakeLists.txt: a Visitor over the frozen build graph.

The generated file is our public face. The contract: modern target-centric
CMake only, byte-deterministic output, a self-describing header, and the
result must build with plain cmake on a machine without Python.
"""

from __future__ import annotations

from cmakeless.model.nodes import ExecutableModel, ProjectModel

CMAKE_MINIMUM_VERSION = "3.25"


def emit_cmakelists(model: ProjectModel, *, tool_version: str) -> str:
    """Generate the complete, standalone CMakeLists.txt for the given model."""
    return _CMakeListsVisitor(model, tool_version).emit()


class _CMakeListsVisitor:
    """Each node type contributes its own section; the traversal stays fixed."""

    def __init__(self, model: ProjectModel, tool_version: str) -> None:
        self._model = model
        self._tool_version = tool_version

    def emit(self) -> str:
        sections = [self._header(), self._preamble()]
        # Declaration order in build.py is meaningless to CMake, so targets
        # are sorted by name to keep the output deterministic and diffable.
        sections.extend(
            self._visit_executable(target)
            for target in sorted(self._model.executables, key=lambda target: target.name)
        )
        return "\n\n".join(sections) + "\n"

    def _header(self) -> str:
        return (
            f"# Generated by cmakeless {self._tool_version} "
            f"from {self._model.source_script}.\n"
            f"# This file is standalone: it builds with plain CMake, no Python needed.\n"
            f"# Prefer editing {self._model.source_script} and regenerating over "
            f"editing this file."
        )

    def _preamble(self) -> str:
        return (
            f"cmake_minimum_required(VERSION {CMAKE_MINIMUM_VERSION})\n"
            f"\n"
            f"project({self._model.name}\n"
            f"    VERSION {self._model.version}\n"
            f"    LANGUAGES CXX\n"
            f")"
        )

    def _visit_executable(self, target: ExecutableModel) -> str:
        lines = [f"add_executable({target.name})", ""]
        lines.extend(self._sources_block(target.name, "PRIVATE", target))
        lines.append("")
        lines.append(
            f"target_compile_features({target.name} PRIVATE cxx_std_{self._model.cpp_std})"
        )
        return "\n".join(lines)

    def _sources_block(self, name: str, visibility: str, target: ExecutableModel) -> list[str]:
        lines = [f"target_sources({name} {visibility}"]
        lines.extend(f"    {source.as_posix()}" for source in sorted(target.sources))
        lines.append(")")
        return lines
