# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Generated toolchain files for the simple cross-compilation cases.

A toolchain with no ``file`` and no ``variables`` is described entirely by
fields (compiler, system name) and generated here, under cmake/toolchains/. A
wrapped toolchain file (Toolchain.from_file) with no ``variables`` is
referenced in place and never rewritten. A wrapped file *with* variables (the
curated gallery's android()/emscripten(), which need cache variables like
ANDROID_ABI seeded before the SDK's own toolchain file runs) still gets a
small generated wrapper here: the variables, then an include() of the
original file.
"""

from __future__ import annotations

from cmakeless.model.nodes import ToolchainModel


def emit_toolchain(toolchain: ToolchainModel, *, tool_version: str, source_script: str) -> str:
    """Generate one toolchain file: fields, variables, and/or a wrapped include.

    Args:
        toolchain: The toolchain to emit; only reached when it has no
            ``file`` or has ``variables`` (see emit_tree()'s wiring).
        tool_version: The cmakeless version stamped into the header.
        source_script: The build description named in the header.

    Returns:
        The full toolchain file text, newline-terminated.
    """
    lines = [
        f"# Generated by cmakeless {tool_version} from {source_script}.",
        f"# Toolchain '{toolchain.name}'. Prefer editing {source_script} and",
        "# regenerating over editing this file.",
    ]
    if toolchain.system_name is not None:
        lines.append(f"set(CMAKE_SYSTEM_NAME {toolchain.system_name})")
    if toolchain.system_processor is not None:
        lines.append(f"set(CMAKE_SYSTEM_PROCESSOR {toolchain.system_processor})")
    lines.extend(f'set({name} "{value}")' for name, value in toolchain.variables)
    if toolchain.compiler is not None:
        lines.append(f"set(CMAKE_CXX_COMPILER {toolchain.compiler})")
    if toolchain.system_name is not None:
        # Cross builds must find programs on the host but everything else
        # in the target sysroot; these four lines are the standard recipe.
        lines.extend(
            (
                "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)",
            )
        )
    if toolchain.file is not None:
        include_path = (
            toolchain.file.as_posix()
            if toolchain.file.is_absolute()
            else f"${{CMAKE_CURRENT_SOURCE_DIR}}/{toolchain.file.as_posix()}"
        )
        lines.append(f'include("{include_path}")')
    return "\n".join(lines) + "\n"
