# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Generated toolchain files for the simple cross-compilation cases.

Wrapped toolchain files (Toolchain.from_file) are referenced in place and
never rewritten; only toolchains described by fields (compiler, system name)
get a file generated here, under cmake/toolchains/.
"""

from __future__ import annotations

from cmakeless.model.nodes import ToolchainModel


def emit_toolchain(toolchain: ToolchainModel, *, tool_version: str, source_script: str) -> str:
    """Generate one simple toolchain file.

    Args:
        toolchain: The generated toolchain to emit; its ``file`` is None.
        tool_version: The cmakeless version stamped into the header.
        source_script: The build description named in the header.

    Returns:
        The full toolchain file text, newline-terminated.
    """
    lines = [
        f"# Generated by cmakeless {tool_version} from {source_script}.",
        f"# Toolchain '{toolchain.name}'. Prefer editing {source_script} and",
        "# regenerating over editing this file.",
    ]
    if toolchain.system_name is not None:
        lines.append(f"set(CMAKE_SYSTEM_NAME {toolchain.system_name})")
    if toolchain.system_processor is not None:
        lines.append(f"set(CMAKE_SYSTEM_PROCESSOR {toolchain.system_processor})")
    if toolchain.compiler is not None:
        lines.append(f"set(CMAKE_CXX_COMPILER {toolchain.compiler})")
    if toolchain.system_name is not None:
        # Cross builds must find programs on the host but everything else
        # in the target sysroot; these four lines are the standard recipe.
        lines.extend(
            (
                "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)",
                "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)",
            )
        )
    return "\n".join(lines) + "\n"
