"""The emitter contract: modern, target-centric, deterministic output."""

from __future__ import annotations

from pathlib import Path

from cmakeless.emitter import emit_cmakelists
from cmakeless.model.nodes import ExecutableModel, ProjectModel

FIXED_VERSION = "1.2.3"


def make_model(*executables: ExecutableModel) -> ProjectModel:
    """Build a minimal frozen project around the given executables."""
    return ProjectModel(
        name="demo",
        version="1.0.0",
        cpp_std=20,
        root_dir=Path("/does/not/matter"),
        source_script="build.py",
        executables=executables,
    )


def test_emits_self_describing_header() -> None:
    """Emits self describing header."""
    text = emit_cmakelists(make_model(), tool_version=FIXED_VERSION)
    first_line = text.splitlines()[0]
    assert first_line == "# Generated by cmakeless 1.2.3 from build.py."


def test_emits_modern_preamble() -> None:
    """Emits modern preamble."""
    text = emit_cmakelists(make_model(), tool_version=FIXED_VERSION)
    assert "cmake_minimum_required(VERSION 3.25)" in text
    assert "project(demo" in text
    assert "VERSION 1.0.0" in text
    assert "LANGUAGES CXX" in text


def test_emits_target_centric_executable() -> None:
    """Emits target centric executable."""
    app = ExecutableModel(name="app", sources=(Path("src/main.cpp"),))
    text = emit_cmakelists(make_model(app), tool_version=FIXED_VERSION)
    assert "add_executable(app)" in text
    assert "target_sources(app PRIVATE" in text
    assert "    src/main.cpp" in text
    assert "target_compile_features(app PRIVATE cxx_std_20)" in text


def test_output_is_deterministic() -> None:
    """Output is deterministic."""
    app = ExecutableModel(name="app", sources=(Path("b.cpp"), Path("a.cpp")))
    model = make_model(app)
    assert emit_cmakelists(model, tool_version=FIXED_VERSION) == emit_cmakelists(
        model, tool_version=FIXED_VERSION
    )


def test_targets_and_sources_are_sorted() -> None:
    """Targets and sources are sorted."""
    zebra = ExecutableModel(name="zebra", sources=(Path("z.cpp"),))
    alpha = ExecutableModel(name="alpha", sources=(Path("b.cpp"), Path("a.cpp")))
    text = emit_cmakelists(make_model(zebra, alpha), tool_version=FIXED_VERSION)
    assert text.index("add_executable(alpha)") < text.index("add_executable(zebra)")
    assert text.index("a.cpp") < text.index("b.cpp")


def test_sources_use_forward_slashes() -> None:
    """Sources use forward slashes."""
    app = ExecutableModel(name="app", sources=(Path("src") / "sub" / "main.cpp",))
    text = emit_cmakelists(make_model(app), tool_version=FIXED_VERSION)
    assert "src/sub/main.cpp" in text
    assert "\\" not in text


def test_no_directory_level_globals() -> None:
    """No directory level globals."""
    app = ExecutableModel(name="app", sources=(Path("src/main.cpp"),))
    text = emit_cmakelists(make_model(app), tool_version=FIXED_VERSION)
    assert "include_directories(" not in text
    assert "file(GLOB" not in text
