"""Every shipped example is a real project that still builds.

The unit suite proves each feature in isolation against a synthetic model.
This proves the things a user actually copies from: the examples/ tree. Each
example is copied to a temp directory and its cmakelessfile.py is executed
exactly as a user would run it, so an API change that breaks documented
usage fails here rather than in somebody's first five minutes.

Gated the same way the end-to-end unit tests are: examples that only
generate need CMake on PATH, and examples that fetch dependencies also need
CMAKELESS_NETWORK_TESTS=1.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from cmakeless import BUILD_SCRIPT_NAME

EXAMPLES_DIR = Path(__file__).resolve().parents[2] / "examples"

requires_cmake = pytest.mark.skipif(shutil.which("cmake") is None, reason="cmake is not on PATH")

# Examples whose dependencies are fetched from the network, or whose
# toolchains/SDKs are not present on an ordinary machine.
NETWORK_EXAMPLES = frozenset(
    {"04_dependencies", "05_testing", "07_python_module", "08_capstone", "11_portability"}
)

# Examples needing a CMake newer than the project-wide floor.
MODULES_EXAMPLES = frozenset({"13_cxx_modules"})


def example_dirs() -> list[Path]:
    """Every numbered example directory, in catalogue order."""
    return sorted(
        path for path in EXAMPLES_DIR.iterdir() if path.is_dir() and path.name[0].isdigit()
    )


def _needs_network(name: str) -> bool:
    """Tell whether an example may reach the network and is therefore gated."""
    return name in NETWORK_EXAMPLES


def _copy_example(source: Path, destination: Path) -> Path:
    """Copy one example to a scratch directory, leaving build output behind."""
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns("build", "__pycache__"))
    return destination


def _run_example(directory: Path) -> subprocess.CompletedProcess[str]:
    """Execute one example's build description the way a user would."""
    return subprocess.run(
        [sys.executable, BUILD_SCRIPT_NAME],
        cwd=directory,
        capture_output=True,
        text=True,
        check=False,
        timeout=900,
    )


@pytest.mark.parametrize("example", example_dirs(), ids=lambda path: path.name)
def test_every_example_has_a_build_description(example: Path) -> None:
    """Every example has a build description."""
    assert (example / BUILD_SCRIPT_NAME).is_file()


@pytest.mark.parametrize("example", example_dirs(), ids=lambda path: path.name)
def test_every_example_is_listed_in_the_catalogue(example: Path) -> None:
    """Every example is listed in the catalogue."""
    catalogue = (EXAMPLES_DIR / "README.md").read_text(encoding="utf-8")
    assert f"({example.name}/)" in catalogue


@requires_cmake
@pytest.mark.parametrize("example", example_dirs(), ids=lambda path: path.name)
def test_every_example_builds(example: Path, tmp_path: Path) -> None:
    """Every example builds."""
    if _needs_network(example.name) and os.environ.get("CMAKELESS_NETWORK_TESTS") != "1":
        pytest.skip("needs CMAKELESS_NETWORK_TESTS=1")
    completed = _run_example(_copy_example(example, tmp_path / example.name))
    if completed.returncode != 0 and example.name in MODULES_EXAMPLES:
        pytest.skip(f"local CMake or generator cannot build modules:\n{completed.stderr[-800:]}")
    assert completed.returncode == 0, (
        f"{example.name} failed to build.\n"
        f"--- stdout ---\n{completed.stdout[-2000:]}\n"
        f"--- stderr ---\n{completed.stderr[-2000:]}"
    )


@requires_cmake
@pytest.mark.parametrize("example", example_dirs(), ids=lambda path: path.name)
def test_every_example_generates_committable_cmake(example: Path, tmp_path: Path) -> None:
    """Every example generates committable cmake."""
    if _needs_network(example.name) and os.environ.get("CMAKELESS_NETWORK_TESTS") != "1":
        pytest.skip("needs CMAKELESS_NETWORK_TESTS=1")
    work = _copy_example(example, tmp_path / example.name)
    if _run_example(work).returncode != 0:
        pytest.skip("example did not build on this machine; covered by the build test")
    generated = (work / "CMakeLists.txt").read_text(encoding="utf-8")
    assert generated.startswith("# Generated by cmakeless ")
    assert "cmake_minimum_required(VERSION " in generated
    assert "file(GLOB" not in generated, "globs must be expanded in Python, not at configure time"
    # Anchored to the line start so target_include_directories() does not match.
    assert not re.search(r"^include_directories\(", generated, re.MULTILINE), (
        "directory-level commands are not target-centric"
    )
