# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""The Toolchain builder: wrap an existing toolchain file or generate one.

The hard cross-compilation cases keep their hand-written toolchain files
(Toolchain.from_file); the simple ones (a different compiler, a well-known
target triple) are generated by the emitter from a few named fields. The
curated gallery (arm_none_eabi, ios, android, emscripten) builds on the same
two primitives: a compiler/system-name description, or a wrapped SDK-provided
file, optionally seeded with extra cache variables the wrapped file expects.
"""

from __future__ import annotations

import os
from pathlib import Path

from cmakeless.errors import ConfigurationError
from cmakeless.model.nodes import ToolchainModel

# The Android NDK's supported ABI names for its own toolchain file.
_ANDROID_ABIS: frozenset[str] = frozenset({"armeabi-v7a", "arm64-v8a", "x86", "x86_64"})

# The ios.cmake-style platform tokens this gallery entry understands.
_IOS_PLATFORMS: frozenset[str] = frozenset({"OS64", "SIMULATOR64", "SIMULATORARM64"})


class Toolchain:
    """A compiler/platform description for cross or pinned builds.

    Attributes:
        name: The toolchain name presets reference (read-only property).
    """

    def __init__(
        self,
        name: str,
        *,
        compiler: str | None = None,
        system_name: str | None = None,
        system_processor: str | None = None,
    ) -> None:
        """Describe a toolchain CMakeless generates a file for.

        Args:
            name: The toolchain name presets reference.
            compiler: The C++ compiler command or path, for example
                "aarch64-linux-gnu-g++".
            system_name: CMAKE_SYSTEM_NAME for cross builds (for example
                "Linux"); None for a host build with a pinned compiler.
            system_processor: CMAKE_SYSTEM_PROCESSOR for cross builds (for
                example "aarch64"); None when not cross-compiling.
        """
        self._name = name
        self._file: Path | None = None
        self._compiler = compiler
        self._system_name = system_name
        self._system_processor = system_processor
        self._variables: tuple[tuple[str, str], ...] = ()

    @classmethod
    def from_file(cls, path: str | Path, *, name: str | None = None) -> Toolchain:
        """Wrap an existing toolchain file, unchanged.

        Args:
            path: The toolchain file, project-root-relative or absolute.
            name: The toolchain name presets reference; None derives it
                from the file's stem ("cmake/rpi4.toolchain.cmake" becomes
                "rpi4.toolchain").

        Returns:
            The wrapping Toolchain.
        """
        file = Path(path)
        toolchain = cls(name if name is not None else file.stem)
        toolchain._file = file
        return toolchain

    @classmethod
    def arm_none_eabi(cls, *, cpu: str = "cortex-m4", name: str = "arm-none-eabi") -> Toolchain:
        """A bare-metal ARM cross toolchain (arm-none-eabi-gcc).

        Args:
            cpu: The target CPU passed to -mcpu, for example "cortex-m4" or
                "cortex-m0plus".
            name: The toolchain name presets reference.

        Returns:
            The generated Toolchain; requires arm-none-eabi-g++ on PATH at
            build time.
        """
        toolchain = cls(
            name, compiler="arm-none-eabi-g++", system_name="Generic", system_processor="arm"
        )
        toolchain._variables = (
            ("CMAKE_CXX_FLAGS_INIT", f"-mcpu={cpu} -mthumb"),
            # No linkable executable exists yet on bare metal; CMake's own
            # compiler-check step must try-compile a static library instead.
            ("CMAKE_TRY_COMPILE_TARGET_TYPE", "STATIC_LIBRARY"),
        )
        return toolchain

    @classmethod
    def ios(
        cls, *, platform: str = "OS64", deployment_target: str = "13.0", name: str | None = None
    ) -> Toolchain:
        """An iOS cross toolchain (device or simulator).

        Args:
            platform: "OS64" (device), "SIMULATOR64" (Intel simulator), or
                "SIMULATORARM64" (Apple Silicon simulator).
            deployment_target: The minimum iOS version, for example "13.0".
            name: The toolchain name presets reference; None derives
                "ios-{platform.lower()}".

        Returns:
            The generated Toolchain; only usable on macOS with Xcode.

        Raises:
            ConfigurationError: When ``platform`` is not a known one.
        """
        if platform not in _IOS_PLATFORMS:
            known = ", ".join(repr(value) for value in sorted(_IOS_PLATFORMS))
            raise ConfigurationError(
                f"Toolchain.ios() received platform={platform!r}, which is not one of: {known}."
            )
        sysroot = "iphonesimulator" if platform.startswith("SIMULATOR") else "iphoneos"
        archs = "x86_64" if platform == "SIMULATOR64" else "arm64"
        toolchain = cls(name if name is not None else f"ios-{platform.lower()}", system_name="iOS")
        toolchain._variables = (
            ("CMAKE_OSX_SYSROOT", sysroot),
            ("CMAKE_OSX_ARCHITECTURES", archs),
            ("CMAKE_OSX_DEPLOYMENT_TARGET", deployment_target),
        )
        return toolchain

    @classmethod
    def android(
        cls, *, ndk: str | Path, abi: str, platform: int = 21, name: str | None = None
    ) -> Toolchain:
        """An Android NDK cross toolchain, wrapping the NDK's own toolchain file.

        Args:
            ndk: The Android NDK installation directory.
            abi: The target ABI: "armeabi-v7a", "arm64-v8a", "x86", or
                "x86_64".
            platform: The minimum Android API level, for example 21.
            name: The toolchain name presets reference; None derives
                "android-{abi}".

        Returns:
            The wrapping Toolchain; existence of the NDK's own toolchain
            file under ``ndk`` is checked at freeze time, same as
            Toolchain.from_file().

        Raises:
            ConfigurationError: When ``abi`` is not a known Android ABI.
        """
        if abi not in _ANDROID_ABIS:
            known = ", ".join(repr(value) for value in sorted(_ANDROID_ABIS))
            raise ConfigurationError(
                f"Toolchain.android() received abi={abi!r}, which is not one of "
                f"the Android NDK's ABIs: {known}."
            )
        toolchain = cls(name if name is not None else f"android-{abi}")
        toolchain._file = Path(ndk) / "build" / "cmake" / "android.toolchain.cmake"
        toolchain._variables = (
            ("ANDROID_ABI", abi),
            ("ANDROID_PLATFORM", f"android-{platform}"),
        )
        return toolchain

    @classmethod
    def emscripten(cls, *, emsdk: str | Path | None = None, name: str = "emscripten") -> Toolchain:
        """An Emscripten (WebAssembly) toolchain, wrapping the SDK's own toolchain file.

        Args:
            emsdk: The Emscripten SDK checkout directory; None reads the
                EMSDK environment variable (set by sourcing emsdk_env.sh /
                emsdk_env.bat).
            name: The toolchain name presets reference.

        Returns:
            The wrapping Toolchain; existence of the SDK's own toolchain
            file is checked at freeze time, same as Toolchain.from_file().

        Raises:
            ConfigurationError: When neither ``emsdk`` nor the EMSDK
                environment variable is set.
        """
        root = Path(emsdk) if emsdk is not None else _emsdk_root_from_env()
        if root is None:
            raise ConfigurationError(
                "Toolchain.emscripten() could not locate the Emscripten SDK: no "
                "emsdk= argument was given and the EMSDK environment variable "
                'is not set. Pass emsdk="/path/to/emsdk", or source '
                "emsdk_env.sh (emsdk_env.bat on Windows) first."
            )
        toolchain = cls(name)
        toolchain._file = (
            root / "upstream" / "emscripten" / "cmake" / "Modules" / "Platform" / "Emscripten.cmake"
        )
        return toolchain

    @property
    def name(self) -> str:
        """The toolchain name presets reference."""
        return self._name

    def __repr__(self) -> str:
        """Developer-facing representation.

        Returns:
            The name and source (file or compiler) of this toolchain.
        """
        if self._file is not None:
            return f"Toolchain(name={self._name!r}, file={self._file.as_posix()!r})"
        return (
            f"Toolchain(name={self._name!r}, compiler={self._compiler!r}, "
            f"system_name={self._system_name!r})"
        )

    def _freeze(self) -> ToolchainModel:
        """Freeze this builder into its immutable model node.

        Returns:
            The ToolchainModel; validation happens on the frozen project.
        """
        return ToolchainModel(
            name=self._name,
            file=self._file,
            compiler=self._compiler,
            system_name=self._system_name,
            system_processor=self._system_processor,
            variables=self._variables,
        )


def _emsdk_root_from_env() -> Path | None:
    """Read the Emscripten SDK checkout directory from the EMSDK variable.

    Returns:
        The checkout directory, or None when EMSDK is not set.
    """
    value = os.environ.get("EMSDK")
    return Path(value) if value else None
