# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""The Toolchain builder: wrap an existing toolchain file or generate one.

The hard cross-compilation cases keep their hand-written toolchain files
(Toolchain.from_file); the simple ones (a different compiler, a well-known
target triple) are generated by the emitter from a few named fields.
"""

from __future__ import annotations

from pathlib import Path

from cmakeless.model.nodes import ToolchainModel


class Toolchain:
    """A compiler/platform description for cross or pinned builds.

    Attributes:
        name: The toolchain name presets reference (read-only property).
    """

    def __init__(
        self,
        name: str,
        *,
        compiler: str | None = None,
        system_name: str | None = None,
        system_processor: str | None = None,
    ) -> None:
        """Describe a toolchain CMakeless generates a file for.

        Args:
            name: The toolchain name presets reference.
            compiler: The C++ compiler command or path, for example
                "aarch64-linux-gnu-g++".
            system_name: CMAKE_SYSTEM_NAME for cross builds (for example
                "Linux"); None for a host build with a pinned compiler.
            system_processor: CMAKE_SYSTEM_PROCESSOR for cross builds (for
                example "aarch64"); None when not cross-compiling.
        """
        self._name = name
        self._file: Path | None = None
        self._compiler = compiler
        self._system_name = system_name
        self._system_processor = system_processor

    @classmethod
    def from_file(cls, path: str | Path, *, name: str | None = None) -> Toolchain:
        """Wrap an existing toolchain file, unchanged.

        Args:
            path: The toolchain file, project-root-relative or absolute.
            name: The toolchain name presets reference; None derives it
                from the file's stem ("cmake/rpi4.toolchain.cmake" becomes
                "rpi4.toolchain").

        Returns:
            The wrapping Toolchain.
        """
        file = Path(path)
        toolchain = cls(name if name is not None else file.stem)
        toolchain._file = file
        return toolchain

    @property
    def name(self) -> str:
        """The toolchain name presets reference."""
        return self._name

    def __repr__(self) -> str:
        """Developer-facing representation.

        Returns:
            The name and source (file or compiler) of this toolchain.
        """
        if self._file is not None:
            return f"Toolchain(name={self._name!r}, file={self._file.as_posix()!r})"
        return (
            f"Toolchain(name={self._name!r}, compiler={self._compiler!r}, "
            f"system_name={self._system_name!r})"
        )

    def _freeze(self) -> ToolchainModel:
        """Freeze this builder into its immutable model node.

        Returns:
            The ToolchainModel; validation happens on the frozen project.
        """
        return ToolchainModel(
            name=self._name,
            file=self._file,
            compiler=self._compiler,
            system_name=self._system_name,
            system_processor=self._system_processor,
        )
