# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(cmake_interop_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

# project.include() from cmakelessfile.py: cmake/print_summary.cmake
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/print_summary.cmake)
print_summary(hello)

# project.include_module() from cmakelessfile.py: CheckCXXCompilerFlag
include(CheckCXXCompilerFlag)

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_17)
