# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(build_language_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

add_custom_command(
    OUTPUT
        generated/version.cpp
    COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/tools/gen_version.py --out ${CMAKE_CURRENT_BINARY_DIR}/generated/version.cpp
    DEPENDS tools/gen_version.py
    COMMENT "Generating version.cpp"
    VERBATIM
)

add_executable(app)

target_sources(app PRIVATE
    generated/version.cpp
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_17)

add_custom_target(cook-assets
    COMMAND python tools/cook.py assets/ --out cooked/
    DEPENDS assets/manifest.json
    VERBATIM
)
