# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.28)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/engine/util.cpp
)

target_sources(engine PUBLIC
    FILE_SET CXX_MODULES FILES
        src/engine/geometry.cppm
        src/engine/shapes.cppm
)

target_compile_features(engine PUBLIC cxx_std_23)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

target_compile_options(engine PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

add_executable(demo_app)

target_sources(demo_app PRIVATE
    src/main.cpp
)

target_sources(demo_app PRIVATE
    FILE_SET CXX_MODULES FILES
        src/app.cppm
)

target_compile_features(demo_app PRIVATE cxx_std_23)

target_compile_options(demo_app PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)
