# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

include(FetchContent)

# fmt 10.2.1: system package when available, pinned source fetch otherwise.
find_package(fmt 10.2.1 QUIET)
if(NOT fmt_FOUND AND NOT TARGET fmt::fmt)
    FetchContent_Declare(fmt
        URL https://github.com/fmtlib/fmt/archive/refs/tags/10.2.1.tar.gz
        URL_HASH SHA256=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    )
    FetchContent_MakeAvailable(fmt)
endif()

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_20)

target_link_libraries(app
    PRIVATE fmt::fmt
)
