# Generated by cmakeless 1.2.3 from build.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing build.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

# fmt 10.2.1: provided by Conan (see conanfile.txt).
find_package(fmt REQUIRED)

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_20)

target_link_libraries(app
    PRIVATE fmt::fmt
)
