# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

include(GenerateExportHeader)

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/audio.cpp
    src/engine.cpp
)

target_include_directories(engine PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

target_compile_features(engine PUBLIC cxx_std_20)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

target_compile_definitions(engine PRIVATE
    ENGINE_INTERNAL
)

target_compile_options(engine PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

target_link_libraries(engine
    PUBLIC headers
)

add_library(headers INTERFACE)

target_include_directories(headers INTERFACE
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

target_compile_features(headers INTERFACE cxx_std_20)

add_library(plugin SHARED)

target_sources(plugin PRIVATE
    src/plugin.cpp
)

target_compile_features(plugin PUBLIC cxx_std_20)

set_target_properties(plugin PROPERTIES POSITION_INDEPENDENT_CODE ON)

generate_export_header(plugin)
target_include_directories(plugin PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
)

target_compile_options(plugin PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

target_link_libraries(plugin
    PRIVATE engine
)

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_20)

target_compile_definitions(app PRIVATE
    GAME_MAX_PLAYERS=8
)

target_compile_options(app PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
    $<$<CXX_COMPILER_ID:GNU,Clang>:-march=native>
)

target_link_libraries(app
    PRIVATE engine
)
