# Generated by cmakeless 1.2.3 from build.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing build.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(opt_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

# Default build type; an active preset overrides it.
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING
        "Build type for the default configuration" FORCE)
endif()

# Project-level LTO default; a preset's own setting wins.
if(NOT DEFINED CMAKE_INTERPROCEDURAL_OPTIMIZATION)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
endif()

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_17)
