# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(options_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

option(MYLIB_BUILD_GUI "Build the Qt front-end" ON)

set(MYLIB_JOBS "4" CACHE STRING "")
