# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(mymath_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

# find_package(Python ...) takes a minimum version, not an exact one:
# this is the highest floor any add_python_module(python_version=...) requested.
find_package(Python 3.13 COMPONENTS Interpreter Development.Module REQUIRED)
# Make pybind11 build against the Python found above, not its own guess.
set(PYBIND11_FINDPYTHON ON)

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/engine.cpp
)

target_compile_features(engine PUBLIC cxx_std_17)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

target_compile_options(engine PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

pybind11_add_module(mymath)

target_sources(mymath PRIVATE
    src/bindings.cpp
)

target_compile_features(mymath PRIVATE cxx_std_17)

target_compile_definitions(mymath PRIVATE
    MYMATH_VERSION=1
)

target_compile_options(mymath PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

target_link_libraries(mymath
    PRIVATE engine
)
