# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(raw_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

# raw_cmake_file from cmakelessfile.py: cmake/extra.cmake
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/extra.cmake)

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/engine.cpp
)

target_compile_features(engine PUBLIC cxx_std_17)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

# raw_cmake from cmakelessfile.py for target 'engine':
set_target_properties(engine PROPERTIES UNITY_BUILD ON)
target_precompile_headers(engine PRIVATE <vector>)
