# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

set(CMAKELESS_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}" CACHE INTERNAL "")
set(CMAKELESS_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}" CACHE INTERNAL "")

include(GNUInstallDirs)

enable_testing()

# Sanitizers are switched on per preset; see CMakePresets.json.
set(CMAKELESS_SANITIZE "" CACHE STRING
    "Sanitizers applied to every target (semicolon-separated)"
)

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/engine.cpp
)

target_include_directories(engine PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

target_compile_features(engine PUBLIC cxx_std_20)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

target_compile_options(engine PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

target_compile_options(engine PRIVATE
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address;-fno-omit-frame-pointer>
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<CXX_COMPILER_ID:MSVC>>:/fsanitize=address>
)

target_link_options(engine PRIVATE
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address>
)

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_compile_features(app PRIVATE cxx_std_20)

target_compile_options(app PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

if(MSVC)
    message(FATAL_ERROR "Target 'app' requests sanitizers MSVC does not support: undefined. Build with Clang or GCC, or drop them from sanitize in cmakelessfile.py.")
endif()

target_compile_options(app PRIVATE
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address;-fsanitize=undefined;-fno-omit-frame-pointer>
    $<$<CXX_COMPILER_ID:MSVC>:/fsanitize=address>
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address;-fno-omit-frame-pointer>
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<CXX_COMPILER_ID:MSVC>>:/fsanitize=address>
)

target_link_options(app PRIVATE
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address;-fsanitize=undefined>
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address>
)

target_link_libraries(app
    PRIVATE engine
)

# Catch2's per-case discovery module (extras/ when fetched from source).
if(catch2_SOURCE_DIR)
    list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)
endif()
include(Catch)

add_executable(engine_tests)

target_sources(engine_tests PRIVATE
    tests/engine_test.cpp
)

target_compile_features(engine_tests PRIVATE cxx_std_20)

target_compile_options(engine_tests PRIVATE
    $<$<CXX_COMPILER_ID:MSVC>:/W4;/permissive->
    $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall;-Wextra;-Wconversion;-Wsign-conversion;-pedantic>
)

target_compile_options(engine_tests PRIVATE
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address;-fno-omit-frame-pointer>
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<CXX_COMPILER_ID:MSVC>>:/fsanitize=address>
)

target_link_options(engine_tests PRIVATE
    $<$<AND:$<IN_LIST:address,${CMAKELESS_SANITIZE}>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-fsanitize=address>
)

target_link_libraries(engine_tests
    PRIVATE Catch2::Catch2WithMain
    PRIVATE engine
)

catch_discover_tests(engine_tests)

install(TARGETS app
    EXPORT demoTargets
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

install(TARGETS engine
    EXPORT demoTargets
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

install(EXPORT demoTargets
    FILE demoTargets.cmake
    NAMESPACE demo::
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/demo
)

include(CMakePackageConfigHelpers)

configure_package_config_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/demoConfig.cmake.in
    ${CMAKE_CURRENT_BINARY_DIR}/demoConfig.cmake
    INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/demo
)

write_basic_package_version_file(
    ${CMAKE_CURRENT_BINARY_DIR}/demoConfigVersion.cmake
    VERSION ${PROJECT_VERSION}
    COMPATIBILITY SameMajorVersion
)

install(FILES
    ${CMAKE_CURRENT_BINARY_DIR}/demoConfig.cmake
    ${CMAKE_CURRENT_BINARY_DIR}/demoConfigVersion.cmake
    DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/demo
)

set(CPACK_PACKAGE_NAME demo)
set(CPACK_PACKAGE_VERSION 1.0.0)
set(CPACK_GENERATOR "TGZ;ZIP")

include(CPack)
