# Generated by cmakeless 1.2.3 from cmakelessfile.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing cmakelessfile.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(vocab_demo
    VERSION 1.0.0
    LANGUAGES CXX
)

add_library(engine STATIC)

target_sources(engine PRIVATE
    src/engine.cpp
)

target_include_directories(engine PRIVATE
    src/engine_internal
)

target_include_directories(engine PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

target_compile_features(engine PUBLIC cxx_std_17)

set_target_properties(engine PROPERTIES POSITION_INDEPENDENT_CODE ON)

add_executable(app)

target_sources(app PRIVATE
    src/main.cpp
)

target_include_directories(app PRIVATE
    src/internal
)

target_compile_features(app PRIVATE cxx_std_20)
