# Generated by cmakeless 1.2.3 from build.py.
# This file is standalone: it builds with plain CMake, no Python needed.
# Prefer editing build.py and regenerating over editing this file.

cmake_minimum_required(VERSION 3.25)

project(demo
    VERSION 1.0.0
    LANGUAGES CXX
)

add_executable(tool)

target_sources(tool PRIVATE
    main.cpp
)

target_compile_features(tool PRIVATE cxx_std_20)
